spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/libr
    username: libr_usr
    password: libr
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      show-sql: true
logging:
  level:
    ROOT: info
    org.springframework.boot.autoconfigure.logging: debug
  file: logfile.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
