spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/libr
    username: libr_usr
    password: libr
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#    show-sql: true
#    hibernate:
  #      ddl-auto: create-drop
logging:
  level:
    ROOT: error
