spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psql:5432/libr
    username: libr_usr
    password: libr
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#        ddl-auto: create-drop
      show-sql: true
logging:
  level:
    ROOT: info