DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS(ID SERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE GENRES(ID SERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE BOOKS(ID SERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255) NOT NULL UNIQUE,
 AUTHOR_ID BIGINT REFERENCES AUTHORS(ID), GENRE_ID BIGINT REFERENCES GENRES(ID));
